### ISSUE TITLE
Token Replacer updating compendium entries

### ISSUE THREAD

**Issue by MSAbaddon** [vtt-lair/token-replacer#53]
Hi there,
I found one more thing that need a fix.
When I drag an actor, who hast already a defined portrait and token art, from a compendium to a scene or import it to the actors tab, token replacer updates both arts even if he can't find images for this actor - he replaces the aldready defined art with Mystery Man.

**Comment by vtt-lair** [comment]
Hi @MSAbaddon 

Can you possibly supply me with more details? My module never replaces with Mystery Man, if it can't find any images for the actor you are dragging it leaves the image on the actor data as is.

I've just tested it against a compendium item that was pulled from D&D Beyond via DnD Beyond Importer, directly from the compendium to the scene (an adult blue dragon) and the image shown on the token as well as on the actor's tab is what was defined in the compendium during the import. I also pulled the item from the compendium to the actor tab and then from there to the scene and also showed the compendium images.

So I'm either misunderstanding what's happening or it's not my module that's causing the issue.

**Comment by MSAbaddon** [comment]
Sure, here the things I did to reproduce this:
- I disabled all modules except Token Replacer
- I keep the standard settings for the module
- I drag the Acolyte from the Monsters (SRD) compendium to the canvas

![image](https://user-images.githubusercontent.com/66370966/107993238-921f2380-6fda-11eb-9136-50e52eeaf4ee.png)

**Comment by MSAbaddon** [comment]
This only happens if you set Token Replacer to automatically replace token artwork & portrait artwork.
Replacing only token artwork or only portrait artwork works fine.

**Comment by vtt-lair** [comment]
Thanks for the extra details. Will check tonight why this is happening.

**Comment by vtt-lair** [comment]
I think this was related to the other bug that you loaded [#52](https://github.com/vtt-lair/token-replacer/issues/52). I fixed that last night, and just ran through your steps quickly and it's working as expected now. So this fix should be roll out with the other some time this week.

**Comment by MSAbaddon** [comment]
Hi,
just tested this and unfortunately token and portrait artwork are still replaced with mytery man :-(

**Comment by vtt-lair** [comment]
Aha! I was testing it with a folder that had acolyte tokens, so it was replacing them. Changing the linked folder to an empty folder, I am able to replicate this.

**Comment by MSAbaddon** [comment]
Can verify this for the monsters compendium.
Quite interesting though - if I drag an actor from Baileywiki's Town Maps to the canvas the replacement with mystery man still happens. Don't know if this happens because those actors have other stuff attached to them via Token Attacher.
